<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PL_Header;
use DB;

class HargaController extends Controller
{
    //
    public function index($idpl) {


        $data2 = PL_HEADER::select(DB::raw ('tab1.NOMER_PACKING_LIST, tab1.GROUP_PACKING, tab1.ID, SUM(tab1.HARGA) AS HARGA'))
        ->from(DB::raw('
        ( SELECT TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
        TRANS_PACKING_LIST_HEADER.ID,
        TRANS_PACKING_LIST_DETAIL.GROUP_PACKING, 
        (CASE WHEN MS_JENIS_PACKING.HARGA_FULL = 1 
            THEN TRANS_PACKING_LIST_HEADER.HARGA_PER_VOLUME_BY_PENGIRIMAN 
            ELSE SUM(TRANS_PACKING_LIST_DETAIL.TOTAL_HARGA_VOLUME) + SUM(TRANS_PACKING_LIST_DETAIL.TOTAL_HARGA_TONASE) END) AS HARGA      
        FROM TRANS_PACKING_LIST_HEADER 
        LEFT JOIN TRANS_PACKING_LIST_dETAIL 
            ON TRANS_PACKING_LIST_HEADER.ID = TRANS_PACKING_LIST_dETAIL.ID_PACKING_HEADER
        LEFT JOIN MS_JENIS_PACKING
            ON TRANS_PACKING_LIST_HEADER.ID_JENIS_PACKING = MS_JENIS_PACKING.ID
        WHERE TRANS_PACKING_LIST_HEADER.TAHUN IN (2019)
        GROUP BY TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
            TRANS_PACKING_LIST_HEADER.ID,
            TRANS_PACKING_LIST_DETAIL.GROUP_PACKING,
            MS_JENIS_PACKING.HARGA_FULL, 
            TRANS_PACKING_LIST_HEADER.HARGA_PER_VOLUME_BY_PENGIRIMAN

        UNION ALL

        SELECT TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
        TRANS_PACKING_LIST_HEADER.ID,
        TRANS_PL_BIAYA_UTAMA_PENGIRIMAN.GROUP_PACKING, 
        TRANS_PL_BIAYA_UTAMA_PENGIRIMAN.HARGA AS HR
        FROM TRANS_PACKING_LIST_HEADER 
        LEFT JOIN TRANS_PL_BIAYA_UTAMA_PENGIRIMAN 
            ON TRANS_PACKING_LIST_HEADER.ID = TRANS_PL_BIAYA_UTAMA_PENGIRIMAN.ID_TRANS_PACKING_LIST_HEADER
        LEFT JOIN MS_BIAYA_UTAMA_JENIS_PENGIRIMAN
            ON MS_BIAYA_UTAMA_JENIS_PENGIRIMAN.ID = TRANS_PL_BIAYA_UTAMA_PENGIRIMAN.ID_BIAYA_UTAMA_JENIS_PENGIRIMAN
        WHERE TRANS_PACKING_LIST_HEADER.TAHUN IN (2019)
            AND TRANS_PACKING_LIST_HEADER.TOTAL_BIAYA > 0
        GROUP BY TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
            TRANS_PACKING_LIST_HEADER.ID,
            TRANS_PL_BIAYA_UTAMA_PENGIRIMAN.GROUP_PACKING, 
            TRANS_PL_BIAYA_UTAMA_PENGIRIMAN.HARGA

        UNION ALL

        SELECT TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
        TRANS_PACKING_LIST_HEADER.ID,
        TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN.GROUP_PACKING, 
        TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN.HARGA 
        FROM TRANS_PACKING_LIST_HEADER 
        LEFT JOIN TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN 
            ON TRANS_PACKING_LIST_HEADER.ID = TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN.ID_TRANS_PACKING_LIST_HEADER
        LEFT JOIN MS_BIAYA_UTAMA_BERDASARKAN_BATAS
            ON MS_BIAYA_UTAMA_BERDASARKAN_BATAS.ID_RUTE_NETWORK = TRANS_PACKING_LIST_HEADER.ID_ROUTE_NETWORK
        WHERE TRANS_PACKING_LIST_HEADER.TAHUN IN (2019)
            AND TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN.ID_RUTE_NETWORK = MS_BIAYA_UTAMA_BERDASARKAN_BATAS.ID_RUTE_NETWORK
            AND TRANS_PACKING_LIST_HEADER.TOTAL_BIAYA > 0
        GROUP BY TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
            TRANS_PACKING_LIST_HEADER.ID,
            TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN.GROUP_PACKING, 
            TRANS_PL_BIAYA_BERDARKAN_KETENTUAN_KHUSUS_PENGIRIMAN.HARGA 

        UNION ALL

        SELECT TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
        TRANS_PACKING_LIST_HEADER.ID,
        TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN.GROUP_PACKING, 
        TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN.HARGA 
        FROM TRANS_PACKING_LIST_HEADER 
        LEFT JOIN TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN 
            ON TRANS_PACKING_LIST_HEADER.ID = TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN.ID_TRANS_PACKING_LIST_HEADER
        LEFT JOIN MS_BIAYA_TAMBAHAN
            ON MS_BIAYA_TAMBAHAN.ID = TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN.ID_BIAYA_TAMBAHAN
        WHERE TRANS_PACKING_LIST_HEADER.TAHUN IN (2019)
            AND TRANS_PACKING_LIST_HEADER.TOTAL_BIAYA > 0
        GROUP BY TRANS_PACKING_LIST_HEADER.NOMER_PACKING_LIST,
            TRANS_PACKING_LIST_HEADER.ID,
            TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN.GROUP_PACKING, 
            TRANS_PL_BIAYA_TAMBAHAN_PENGIRIMAN.HARGA 

        ) as tab1
        
        '))
        ->where('tab1.ID', $idpl)
        ->groupBy('tab1.NOMER_PACKING_LIST', 'tab1.GROUP_PACKING', 'tab1.ID')
        ->get();

    

        
        return response()->json($data2);
      }
}
